<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<script>
			const p1 = new Promise((
				resolve,
				reject
			) => {
				setTimeout(() => {
					resolve('data1')
				}, 1000)
			});
			const p2 = new Promise((
				resolve,
				reject
			) => {
				setTimeout(() => {
					//resolve('data2')
					reject('err')
				}, 1000)
			});
			// 返回一个成功的Promise对象
			const result = Promise.allSettled([p1, p2]);
			console.log(result)
			// 有一个Promise对象失败 则返回的是一个失败的Promise
			const result1 = Promise.all([p1, p2])
			console.log(result1)
		</script>
	</body>
</html>
